language: java
sudo: required
services:
- docker
env:
- DOCKER_COMPOSE_VERSION=1.9.0
jdk:
- oraclejdk8
install:
- bash scripts/install.sh rmspogfo
- cp target/rmspogfo.war docker/tomcat/
before_script:
- pushd docker
- docker-compose up -d
- popd
script:
- mvn test
- bash scripts/coveralls.sh
- mvn integration-test
after_script:
- bash scripts/gitbook.sh
before_deploy:
- bash scripts/build.sh rmspogfo
- bash scripts/tag.sh
deploy:
  provider: releases
  api_key:
    secure: ng2aVvt5oA/XuvVgOsJBGbunGi8Q/r8BxR9siLzFxrBY/3rXwjd9GmQQ2K1kqfeyAMrM4J3ef8QKr9RB4rd63IscTaLCFiyP8H74oEB0PSoFaZ9kL53tcR2k58ObSnQCHQLX3+X8HwC0+/ENaMpxntpXeT85EjZ0VHjghA/SE7MiXNPfyr4+I6+2GRtv2UEU6CaM0VNZvcHWhgAXCAji9aPq0/0UQXyIzjEi4RSBUvAYuuePZuryg8+9yRVk07vgsLw9k1mKfhBUtJUmuUCoBUjBc5iP5vh6lyyjbdLBePng+JejZDu0h17Qn/1zc8xwyTTTpCGj4td6gbgDjD6rx8q5w70znydTJyHXFrg8WAHEClXDCXvGgu5BtL7By0+XP4IRGAN7c96RHCQlkGUy/bBtG9ivrtyYGZd4G5Nk/cdiBkztz+YS1o84aLfrCnTPxgz6yI76vebHyZvXQJ1aa6Pb80Y6AzEQSbFLgp8jCt9X3SaHN66Ue4gV5Gnggr+u2gXBALdYau9gcLnKDTBv8MdAuFXn0dp0IbLw4sGF3BYB12TSaMGBKtdedQmkcUhUnUgn6cNeAhZbQUaVYFoFbqDYqJ5xF7WpVFoEL8hy0oUJu+onO2QgNjEY49a34sQhYjj+DAkQQ2Iop+g9oestEQzVHlSbDJE0wfll+yp9r/Y=
  file: target/rmspogfo.war
  skip_cleanup: true
  on:
    repo: InseeFr/Pogues-Back-Office
    branch: zenika-dev
    tags: false
branches:
  except:
  - "/^v[0-9]+\\.[0-9]+\\.[0-9]+.*/"
