language: java
jdk:
- oraclejdk8
sudo: required
services:
- docker
addons:
  sauce_connect: true
env:
- DOCKER_COMPOSE_VERSION=1.9.0
install:
- bash scripts/install.sh
- bash scripts/build.sh rmspogfo
- cp target/rmspogfo.war docker/tomcat/
before_script:
- sudo sysctl -w vm.max_map_count=262144
- pushd docker
- docker-compose up -d
- popd
script:
- mvn test
- bash scripts/coveralls.sh
- mvn integration-test
- bash scripts/e2e.sh
after_success:
- bash scripts/tag.sh
deploy:
  provider: releases
  api_key:
    secure: p7vVj36CMfn1gdoV4XUyx3Vb45x8KV0OqTh2TpjcPLXIxuW3SPKMFszhIRSXtgScz6GpAbFUhJFEj//DJtRyPSeirnDoc5TR49FgZVj5f64II9M1M1fiEto+bktv3MFQ97MAotTre4ac59+3fNLNGsc38H22EyUxLS6LBDQ8eUzgeBu92sefbH1zClDri/RAeyZLuT6daGGPGAQWywAHjz7NI9xw2pJQ27eWCRCh64VBOsDiTq+J9FzenUnbHcJY/ZIVtddR2ERFG/uNd4bLM938YVvT3qrE9HC2nLcyMw9ZqwqM/uH7m2ljWH2SlI03Ed9HWfQ+I44tLYF2EQyPY7nlh97ottyCslfB41QvokTqwrF2IiXhVyzC0kKtSYsmw9x8sh7ee1G26z9qr5oL8LFd9572fYvYaRkP7JlUtk2JbCp7IToC3o25BJRuv2pao8BQLH4Vb6heELWuoiVi+iQ0yJFkB6dASNejdiKGjsr43Yy66yOP9lWTTEYmbaVDLMHQRJ10R6omSVdYR3xveKeCF+i+nfQaBWvIcHngIzsCWguD7mzItgYQ2VnEzV8Mxy3BKTKbPOIClJGzGwitZycxU6TTKBzMwJouW18Qbw5Pr+tyrTCF7wtoAlTy/MCVYefYKiP364X3YBHyqg93MZkEIal0iPGdjSwSOOy8kwU=
  file: target/rmspogfo.war
  skip_cleanup: true
  on:
    repo: InseeFr/Pogues-Back-Office
    branch: zenika-dev
    condition: -f "$TRAVIS_BUILD_DIR/.tag" && $(cat "$TRAVIS_BUILD_DIR/.tag") =~ v[0-9]\.[0-9]\.[0-9].*
    tags: false
after_script:
- bash scripts/gitbook.sh
#branches:
#  except:
#  - "/^v[0-9]+\\.[0-9]+\\.[0-9]+.*/"
