sudo: required
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.9.0
language: java
jdk:
  - oraclejdk8
install:
  - bash scripts/install.sh rmspogfo
  - cp target/rmspogfo.war docker/tomcat/
before_script:
  - pushd docker
  - docker-compose up -d
  - popd
script:
  - mvn test
  - bash scripts/coveralls.sh
  - mvn integration-test
after_script:
  - bash scripts/gitbook.sh
  - bash scripts/build.sh rmspogfo

