sudo: required
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.4.2
language: java
jdk:
  - oraclejdk8
script: mvn test
install:
  - mvn clean install -DskipTests
  - mv target/*.war docker/tomcat/rmspogfo.war
before_script:
  - pushd docker
      docker-compose up
    popd
script:
  - mvn test