sudo: required
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.9.0
language: java
jdk:
  - oraclejdk8
before_install:
  - npm install -g gitbook
install:
  - mvn clean install -DskipTests
  - cp target/*.war docker/tomcat/rmspogfo.war
before_script:
  - pushd docker
  - docker-compose up -d
  - popd
script:
  - mvn test
after_sucess:
  - bash scripts/gitbook.sh

