sudo: required
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.9.0
language: java
jdk:
  - oraclejdk8
install:
  - mvn clean install -DskipTests
  - cp target/*.war docker/tomcat/rmspogfo.war
before_script:
  - pushd docker
  - docker-compose up -d
  - popd
script:
  - mvn test
deploy:
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  script:
    - pushd docs
    - gitbook install
    - gitbook build
    - mv _book /tmp/_book
    - popd
    - git checkout gh-pages
    - mv /tmp/_book/* .
    - git commit -m "Update documentation from travis"
    - git push