version: "2"

services:
  ldap:
    build: ./ldap
    networks:
      intra:
        ipv4_address: 172.20.0.1
    volumes:
      - "./ldap/db:/db"
  postgresql:
    build: ./postgresql
    networks:
      intra:
        ipv4_address: 172.20.0.2
    volumes:
      - "./postgresql/db/data.sql:/docker-entrypoint-initdb.d/data.sql"
  elastic:
    build: ./elastic
    environment:
      - http.host=0.0.0.0
      - xpack.security.enabled=false
    networks:
      intra:
        ipv4_address: 172.20.0.3
  colectica:
    build: ./colectica
    networks:
      intra:
        ipv4_address: 172.20.0.4
    volumes:
      - ./colectica/app/db.json:/usr/src/app/db.json
      - ./colectica/app/routes.json:/usr/src/app/routes.json
      - ./colectica/app/middleware.js:/usr/src/app/middleware.js
  tomcat:
    build: ./tomcat
    environment:
      - fr.insee.pogues.env=qa
    volumes:
      - "./tomcat/rmspogfo.war:/usr/local/tomcat/webapps/rmspogfo.war"
      - "./tomcat/pogues-bo.properties:/usr/local/tomcat/webapps/rmspogfo.properties"
    networks:
      - intra
    ports:
      - "8080:8080"
networks:
  intra:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.28.5.0/24