version: "2"

services:
  ldap:
    build: ./ldap
  postgresql:
    build: ./postgresql
  tomcat:
    build: ./tomcat
    volumes:
      - "./tomcat/rmspogfo.war:/usr/local/tomcat/webapps/rmspogfo.war"
    links:
      - "postgresql:db"
      - "ldap:ldap"
    ports:
      - "8080:8080"