version: "2"

services:
  ldap:
    build: ./ldap
    networks:
      intra:
        ipv4_address: 172.20.0.1
  postgresql:
    build: ./postgresql
    networks:
      intra:
        ipv4_address: 172.20.0.2
  elastic:
    build: ./elastic
    networks:
      intra:
        ipv4_address: 172.20.0.3
  colectica:
    build: ./colectica
    command: -w db.json --id Identifier
    networks:
      intra:
        ipv4_address: 172.20.0.4
    volumes:
      - ./colectica/db.json:/app/db.json
    restart: always
  tomcat:
    build: ./tomcat
    volumes:
      - "./tomcat/rmspogfo.war:/usr/local/tomcat/webapps/rmspogfo.war"
    networks:
      - intra
    ports:
      - "8080:8080"
networks:
  intra:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.28.5.0/24