version: "2"

services:
  ldap:
    build: ./ldap
  postgresql:
    build: ./postgresql
    ports:
      - "15432:5432"
  tomcat:
    build: ./tomcat
    volumes:
      - "./tomcat/pogues.war:/usr/local/tomcat/webapps/pogues.war"
    links:
      - "postgresql:db"
      - "ldap:ldap"
    ports:
      - "8080:8080"