version: '2.1'

services:
  ldap:
    build: ./ldap
    networks:
      back:
        ipv4_address: 172.20.0.21
    volumes:
      - "./ldap/db:/db"
    ports:
      - "389:389"
  postgresql:
    build: ./postgresql
    networks:
      back:
        ipv4_address: 172.20.0.22
    volumes:
      - "./postgresql/db/data.sql:/docker-entrypoint-initdb.d/data.sql"
    ports:
      - "5432:5432"
  #elastic:
  #  build: ./elastic
  #  environment:
  #    - http.host=0.0.0.0
  #    - xpack.security.enabled=false
  #  networks:
  #    intra:
  #      ipv4_address: 172.20.0.3     
  colectica:
    build: ./colectica
    networks:
      back:
        ipv4_address: 172.20.0.24
    volumes:
      - ./colectica/app/db.json:/usr/src/app/db.json
      - ./colectica/app/routes.json:/usr/src/app/routes.json
      - ./colectica/app/middleware.js:/usr/src/app/middleware.js
    ports:
      - "3000:3000"
  tomcat:
    build: ./pogues-bo
    environment:
      - fr.insee.pogues.env=qa
    volumes:
      - "./tomcat/rmspogfo.war:/usr/local/tomcat/webapps/rmspogfo.war"
      - "./tomcat/ddi-access-services.war:/usr/local/tomcat/webapps/ddi-access-services.war"
      - "./tomcat/rmspogfo.properties:/usr/local/tomcat/webapps/rmspogfo.properties"
      - "./tomcat/ddi-access-services.properties:/usr/local/tomcat/webapps/ddi-access-services.properties"
    networks:
      - back
    ports:
      - "8080:8080"
  exist:
    build: ./eXist
    networks:
      back:
        ipv4_address: 172.20.0.25
    ports:
      - "9080:8080"
  exist-seed:
    build:
      context: ./eXist-seed
      args:
        - HTTP_PROXY=$HTTP_PROXY
    depends_on:
      - exist
    volumes:
      - ./eXist-seed/app:/opt/exist/app
      - ./eXist-seed/db:/opt/exist/db
      - ./eXist-seed/system:/opt/exist/system
    networks:
      back:
networks:
  back:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
